[package]
name = "backend"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
axum = "0.7.5"
serde = { version = "1.0.214", features = ["derive"] }
tokio = { version = "1.40.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["full"] }
once_cell = "1.20.2"